import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { AppLayout } from "@/components/AppLayout";
import { PageTransition, StaggerContainer, StaggerItem } from "@/components/MotionWrappers";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer } from "recharts";
import { ArrowRight, Calendar, FolderKanban, Flame, Trophy, Sparkles, TrendingUp, Hand, Users, Heart, MessageCircle, FileText } from "lucide-react";
import { useSkillData, skillTagsDefault as skillTags, useDeadlines, useActiveProjects, useCurrentUserProfile } from "@/lib/db";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { ensureValidRadarData } from "@/lib/utils";
import { useState, useEffect } from "react";
import { getCommunityPosts, CommunityPost } from "@/lib/communityDb";
import { formatDistanceToNow } from "date-fns";
import { th } from "date-fns/locale";

const FALLBACK_SKILL_DATA = [
  { skill: "Communication", value: 10, fullMark: 100 },
  { skill: "Teamwork", value: 10, fullMark: 100 },
  { skill: "Problem Solving", value: 10, fullMark: 100 },
  { skill: "Adaptability", value: 10, fullMark: 100 },
  { skill: "Time Management", value: 10, fullMark: 100 },
];

const mockCommunityFeed = [
  {
    id: 1,
    author: "น้องส้ม โอ",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Som",
    time: "2 ชั่วโมงที่แล้ว",
    content: "แจกสรุปชีทเรียน Data Structures บทที่ 4-5 สรุปให้แล้วแบบเข้าใจง่าย ควรอ่านก่อนสอบมิดเทอมจ้า 📚✨",
    tags: ["Data Structure", "สรุปสอบ", "Year 2"],
    likes: 45,
    comments: 12,
    type: "sheet"
  },
  {
    id: 2,
    author: "พี่เอก วิศวะ",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Eak",
    time: "5 ชั่วโมงที่แล้ว",
    content: "ใครกำลังหาเพื่อนทำโปรเจกต์ AI/ML พรุ่งนี้เจอกันที่ตึกสมาร์ทนะ ขาดคนทำ Frontend 1 ตำแหน่ง 🚀",
    tags: ["หาทีม", "AI/ML", "Frontend"],
    likes: 18,
    comments: 8,
    type: "post"
  }
];

const Dashboard = () => {
  const { data: fetchSkillData = [] } = useSkillData();
  const [careerInsight, setCareerInsight] = useState<any>(null);
  const [feed, setFeed] = useState<CommunityPost[]>([]);

  useEffect(() => {
    getCommunityPosts().then(data => setFeed(data.slice(0, 3)));
  }, []);

  useEffect(() => {
    // Try to load cached career insight generated by LLM
    const cached = localStorage.getItem("ku_career_insight");
    if (cached) {
      try {
        const parsed = JSON.parse(cached);
        if (parsed && parsed.summary) {
          setCareerInsight(parsed.summary);
        }
      } catch(e) {}
    }
  }, []);

  const { data: deadlines = [] } = useDeadlines();
  const { data: activeProjects = [] } = useActiveProjects();
  const { profile: userProfile } = useCurrentUserProfile();

  const skillData = userProfile?.profileAnalysis?.radarData || fetchSkillData;
  const userSkillTags = userProfile?.profileAnalysis?.tags || skillTags;

  const navigate = useNavigate();
  const validProjects = activeProjects && activeProjects.length > 0 ? activeProjects : [];
  const totalProgress = validProjects.length > 0 ? Math.round(validProjects.reduce((a, p) => a + (p.progress || 0), 0) / validProjects.length) : 0;
  const safeSkillData = ensureValidRadarData(skillData, FALLBACK_SKILL_DATA);
  const hasSkillData = skillData.length > 0;
  const hasDeadlines = deadlines.length > 0;
  const hasProjects = activeProjects.length > 0;
  const displayName = userProfile?.name?.trim() ? userProfile.name.split(/\s+/)[0] : "คุณ";
  const careerTitle = careerInsight ? careerInsight.title : "ยังไม่มีคำแนะนำทางอาชีพ";
  const careerScore = careerInsight ? typeof careerInsight.matchScore === "number" ? careerInsight.matchScore : 0 : 0;

  return (
    <AppLayout title="Dashboard" hideHeader>
      <PageTransition>
        {/* ========== MOBILE LAYOUT ========== */}
        <div className="md:hidden space-y-5 overflow-x-hidden">
          {/* Hero Greeting */}
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.35, ease: "easeOut" }}
            className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-primary via-primary to-secondary px-5 py-5 text-primary-foreground"
          >
            <div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-white/8" />
            <div className="absolute -bottom-4 -left-4 h-24 w-24 rounded-full bg-white/5" />
            <div className="relative z-10">
              <p className="text-sm font-medium opacity-80">สวัสดี <Hand className="h-4 w-4 inline" /></p>
              <h2 className="mt-0.5 text-[26px] font-extrabold leading-tight">{displayName}</h2>
              <p className="mt-1.5 text-sm opacity-70">ทักษะของคุณกำลังเติบโต <Sparkles className="h-4 w-4 inline ml-1 text-yellow-500" /></p>

              <div className="mt-5 grid grid-cols-3 gap-2">
                {[
                  { icon: Flame, value: "7", label: "Streak" },
                  { icon: Trophy, value: `${careerScore}%`, label: "Match" },
                  { icon: TrendingUp, value: `${totalProgress}%`, label: "Progress" },
                ].map((stat) => (
                  <div key={stat.label} className="rounded-2xl bg-white/12 px-2 py-2.5 text-center backdrop-blur-sm">
                    <stat.icon className="mx-auto h-4.5 w-4.5 opacity-90" />
                    <p className="mt-1 text-[17px] font-extrabold leading-tight">{stat.value}</p>
                    <p className="text-[10px] font-medium opacity-70">{stat.label}</p>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>

          {/* Career Recommendation */}
          <motion.div initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.12 }}>
            <button onClick={() => navigate("/career")} className="flex w-full items-center gap-3.5 rounded-2xl border border-border/50 bg-card p-4 text-left active:scale-[0.98] transition-transform">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-primary/8">
                <Sparkles className="h-6 w-6 text-primary" />
              </div>
              <div className="min-w-0 flex-1">
                <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">AI แนะนำ</p>
                <p className="truncate text-[15px] font-bold text-foreground">{careerTitle}</p>
                <div className="mt-0.5 flex items-center gap-1.5">
                  <span className="text-base font-extrabold text-primary">{careerScore}%</span>
                  <span className="text-[11px] text-muted-foreground">match</span>
                </div>
              </div>
              <ArrowRight className="h-5 w-5 shrink-0 text-muted-foreground/50" />
            </button>
          </motion.div>

          {/* Deadlines - Horizontal scroll */}
          <div>
            <h3 className="mb-2.5 flex items-center gap-2 text-[15px] font-bold text-foreground">
              <Calendar className="h-4 w-4 text-primary" /> เดดไลน์
            </h3>
            <div className="flex gap-2.5 overflow-x-auto pb-1 scrollbar-hide">
              {hasDeadlines ? deadlines.map((d, i) => (
                <motion.div
                  key={d.title}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.15 + i * 0.06 }}
                >
                  <div className="min-w-[150px] shrink-0 rounded-2xl border border-border/50 bg-card p-3.5">
                    <p className="text-[11px] font-bold text-primary">{d.date}</p>
                    <p className="mt-1 text-[13px] font-semibold leading-tight text-foreground">{d.title}</p>
                    <p className="mt-0.5 text-[11px] text-muted-foreground">{d.course}</p>
                  </div>
                </motion.div>
              )) : (
                <div className="min-w-[220px] rounded-2xl border border-dashed border-border/60 bg-card p-4 text-sm text-muted-foreground">
                  ยังไม่มีเดดไลน์ใน Firestore
                </div>
              )}
            </div>
          </div>

          {/* Active Projects */}
          <div>
            <h3 className="mb-2.5 flex items-center gap-2 text-[15px] font-bold text-foreground">
              <FolderKanban className="h-4 w-4 text-primary" /> โปรเจกต์
            </h3>
            <div className="space-y-2.5">
              {hasProjects ? activeProjects.map((p, i) => (
                <motion.div
                  key={p.name}
                  initial={{ opacity: 0, x: -8 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.2 + i * 0.06 }}
                >
                  <button onClick={() => navigate("/projects")} className="flex w-full items-center gap-3.5 rounded-2xl border border-border/50 bg-card p-3.5 active:scale-[0.98] transition-transform">
                    <div className="relative h-12 w-12 shrink-0">
                      <svg className="h-12 w-12 -rotate-90" viewBox="0 0 48 48">
                        <circle cx="24" cy="24" r="20" fill="none" stroke="hsl(var(--accent))" strokeWidth="4" />
                        <circle cx="24" cy="24" r="20" fill="none" stroke="hsl(var(--primary))" strokeWidth="4"
                          strokeDasharray={`${((p.progress || 0) / 100) * 125.6} 125.6`} strokeLinecap="round" />
                      </svg>
                      <span className="absolute inset-0 flex items-center justify-center text-xs font-bold text-foreground">{p.progress || 0}%</span>
                    </div>
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-[14px] font-semibold text-foreground">{p.name}</p>
                      <p className="text-[11px] text-muted-foreground">{p.members} สมาชิก</p>
                    </div>
                    <ArrowRight className="h-4 w-4 shrink-0 text-muted-foreground/40" />
                  </button>
                </motion.div>
              )) : (
                <div className="rounded-2xl border border-dashed border-border/60 bg-card p-4 text-sm text-muted-foreground">
                  ยังไม่มีโปรเจกต์ใน Firestore
                </div>
              )}
            </div>
          </div>

          {/* Skill Radar */}
          <div className="rounded-2xl border border-border/50 bg-card p-4">
            <h3 className="mb-1 text-[15px] font-bold text-foreground">Skill Identity</h3>
            <div className="mx-auto h-48 w-full min-h-[192px]">
              <ResponsiveContainer width="100%" height="100%">
                <RadarChart data={safeSkillData}>
                  <PolarGrid stroke="hsl(140 10% 90%)" />
                  <PolarAngleAxis dataKey="skill" tick={{ fill: "hsl(150 5% 45%)", fontSize: 10 }} />
                  <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                  <Radar dataKey="value" stroke="hsl(153 100% 20%)" fill="hsl(153 100% 20%)" fillOpacity={0.15} strokeWidth={2} />
                </RadarChart>
              </ResponsiveContainer>
            </div>
            {!hasSkillData && (
              <p className="mt-2 text-xs text-muted-foreground">ยังไม่มีข้อมูล Skill Data ใน Firestore</p>
            )}
            <div className="mt-1 flex flex-wrap gap-1.5">
              {userSkillTags.map((tag: string) => (
                <Badge key={tag} variant="secondary" className="rounded-full bg-accent text-accent-foreground border-0 px-2.5 py-0.5 text-[10px] font-medium">
                  {tag}
                </Badge>
              ))}
            </div>
          </div>

          {/* Community & Study Materials Mobile */}
          <div>
            <div className="mb-2.5 flex items-center justify-between">
              <h3 className="flex items-center gap-2 text-[15px] font-bold text-foreground">
                <Users className="h-4 w-4 text-primary" /> สังคมและชีทเรียน
              </h3>
              <span onClick={() => window.location.href = "/community"} className="text-[11px] font-medium text-primary cursor-pointer hover:underline">ดูทั้งหมด</span>
            </div>
            <div className="space-y-3">
              {(feed.length > 0 ? feed : mockCommunityFeed.slice(0,2)).map((post) => (
                <motion.div key={post.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}>
                  <div className="rounded-2xl border border-border/50 bg-card p-4">
                    <div className="flex items-center gap-3">
                      <img src={post.avatar} alt={post.author} className="h-8 w-8 rounded-full bg-accent" />
                      <div className="min-w-0 flex-1">
                        <p className="text-[13px] font-bold text-foreground truncate">{post.author}</p>
                        <p className="text-[10px] text-muted-foreground">{post.createdAt?.toDate ? formatDistanceToNow(post.createdAt.toDate(), { addSuffix: true, locale: th }) : (post as any).time || "เพิ่งจะ"}</p>
                      </div>
                      {post.type === "sheet" && (
                        <Badge variant="secondary" className="rounded bg-primary/10 text-primary border-0 px-1.5 py-0">
                          <FileText className="mr-1 h-3 w-3" /> แจกชีท
                        </Badge>
                      )}
                    </div>
                    <div className="prose prose-sm dark:prose-invert max-w-none mt-2.5 text-[13px] leading-relaxed text-foreground/90 line-clamp-4">
                      <ReactMarkdown remarkPlugins={[remarkGfm]}>{post.content}</ReactMarkdown>
                    </div>
                    <div className="mt-3 flex gap-4 text-muted-foreground">
                      <button className="flex items-center gap-1 text-[11px] font-medium hover:text-primary">
                        <Heart className="h-3.5 w-3.5" /> {post.likes}
                      </button>
                      <button className="flex items-center gap-1 text-[11px] font-medium hover:text-primary">
                        <MessageCircle className="h-3.5 w-3.5" /> {post.comments}
                      </button>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        {/* ========== DESKTOP LAYOUT ========== */}
        <div className="hidden md:block">
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-foreground">Welcome back, {displayName} <Hand className="h-5 w-5 inline ml-1" /></h2>
            <p className="text-muted-foreground">Your skills are growing. Keep building your future.</p>
          </div>

          <div className="grid gap-6 lg:grid-cols-3">
            <div className="space-y-6 lg:col-span-2">
              <StaggerItem>
                <Card className="rounded-2xl border-border/50">
                  <CardHeader><CardTitle className="text-lg">Your Skill Identity</CardTitle></CardHeader>
                  <CardContent>
                    <div className="mx-auto h-72 w-full max-w-md">
                      <ResponsiveContainer width="100%" height="100%">
                        <RadarChart data={safeSkillData}>
                          <PolarGrid stroke="hsl(140 10% 90%)" />
                          <PolarAngleAxis dataKey="skill" tick={{ fill: "hsl(150 5% 45%)", fontSize: 12 }} />
                          <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                          <Radar dataKey="value" stroke="hsl(153 100% 20%)" fill="hsl(153 100% 20%)" fillOpacity={0.15} strokeWidth={2} />
                        </RadarChart>
                      </ResponsiveContainer>
                    </div>
                    {!hasSkillData && (
                      <p className="mt-3 text-sm text-muted-foreground">ยังไม่มีข้อมูล Skill Data ใน Firestore</p>
                    )}
                    <div className="mt-4 flex flex-wrap gap-2">
                      {userSkillTags.map((tag: string) => (
                        <Badge key={tag} variant="secondary" className="rounded-full bg-accent text-accent-foreground border-0 px-3 py-1 text-xs font-medium transition-colors duration-200 hover:bg-primary hover:text-primary-foreground">
                          {tag}
                        </Badge>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              </StaggerItem>

              <StaggerItem>
                <div className="mt-6 flex items-center justify-between pb-2">
                  <h3 className="text-xl font-bold text-foreground">Community & Study Sheets</h3>
                  <Button onClick={() => window.location.href = "/community"} variant="ghost" size="sm" className="text-primary hover:text-primary/80">View all</Button>
                </div>
                <div className="grid gap-4 sm:grid-cols-2">
                  {(feed.length > 0 ? feed : mockCommunityFeed).map((post) => (
                    <Card key={post.id} className="rounded-2xl border-border/50 hover:shadow-md transition-shadow">
                      <CardContent className="p-4">
                        <div className="flex items-center gap-3">
                          <img src={post.avatar} alt={post.author} className="h-10 w-10 rounded-full bg-accent" />
                          <div className="min-w-0">
                            <p className="text-sm font-semibold truncate text-foreground">{post.author}</p>
                            <p className="text-xs text-muted-foreground">{post.createdAt?.toDate ? formatDistanceToNow(post.createdAt.toDate(), { addSuffix: true, locale: th }) : (post as any).time || "เพิ่งจะ"}</p>
                          </div>
                          {post.type === "sheet" && (
                            <Badge variant="secondary" className="ml-auto bg-primary/10 text-primary border-0">
                              <FileText className="mr-1 h-3 w-3" /> Free Sheet
                            </Badge>
                          )}
                        </div>
                        <div className="prose prose-sm dark:prose-invert max-w-none mt-3 text-sm leading-relaxed text-foreground/90 line-clamp-3">
                          <ReactMarkdown remarkPlugins={[remarkGfm]}>{post.content}</ReactMarkdown>
                        </div>
                        <div className="mt-4 flex flex-wrap gap-1.5">
                          {post.tags.map((t) => (
                            <Badge key={t} variant="outline" className="rounded-md border-border/50 px-2 py-0 text-[10px] font-normal text-muted-foreground shadow-sm">
                              #{t}
                            </Badge>
                          ))}
                        </div>
                        <div className="mt-4 flex items-center gap-4 text-muted-foreground">
                          <button className="flex items-center gap-1.5 text-xs hover:text-primary transition-colors">
                            <Heart className="h-4 w-4" /> {post.likes}
                          </button>
                          <button className="flex items-center gap-1.5 text-xs hover:text-primary transition-colors">
                            <MessageCircle className="h-4 w-4" /> {post.comments}
                          </button>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </StaggerItem>
            </div>

            <StaggerContainer className="space-y-6">
              <StaggerItem>
                <Card className="card-hover rounded-2xl border-border/50">
                  <CardHeader className="pb-3"><CardTitle className="text-base">Career Recommendation</CardTitle></CardHeader>
                  <CardContent>
                    <p className="text-lg font-semibold text-foreground">{careerTitle}</p>
                    <div className="mt-2 flex items-center gap-2">
                      <span className="text-2xl font-bold text-primary">{careerScore}%</span>
                      <span className="text-sm text-muted-foreground">match</span>
                    </div>
                    <Button variant="ghost" onClick={() => navigate("/career")} className="mt-3 gap-1 px-0 text-primary hover:bg-transparent hover:text-primary/80">
                      View Insight <ArrowRight className="h-4 w-4" />
                    </Button>
                  </CardContent>
                </Card>
              </StaggerItem>
              <StaggerItem>
                <Card className="rounded-2xl border-border/50">
                  <CardHeader className="pb-3">
                    <CardTitle className="flex items-center gap-2 text-base"><Calendar className="h-4 w-4 text-primary" /> Upcoming Deadlines</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    {hasDeadlines ? deadlines.map((d) => (
                      <div key={d.title} className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium text-foreground">{d.title}</p>
                          <p className="text-xs text-muted-foreground">{d.course}</p>
                        </div>
                        <span className="text-xs text-muted-foreground">{d.date}</span>
                      </div>
                    )) : (
                      <p className="text-sm text-muted-foreground">ยังไม่มีเดดไลน์ใน Firestore</p>
                    )}
                  </CardContent>
                </Card>
              </StaggerItem>
              <StaggerItem>
                <Card className="rounded-2xl border-border/50">
                  <CardHeader className="pb-3">
                    <CardTitle className="flex items-center gap-2 text-base"><FolderKanban className="h-4 w-4 text-primary" /> Active Projects</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {hasProjects ? activeProjects.map((p) => (
                      <div key={p.name}>
                        <div className="mb-1 flex items-center justify-between">
                          <p className="text-sm font-medium text-foreground">{p.name}</p>
                          <span className="text-xs text-muted-foreground">{p.progress || 0}%</span>
                        </div>
                        <Progress value={p.progress || 0} className="h-2 bg-accent [&>div]:bg-primary" />
                      </div>
                    )) : (
                      <p className="text-sm text-muted-foreground">ยังไม่มีโปรเจกต์ใน Firestore</p>
                    )}
                  </CardContent>
                </Card>
              </StaggerItem>
            </StaggerContainer>
          </div>
        </div>
      </PageTransition>
    </AppLayout>
  );
};

export default Dashboard;
